### PR TITLE
Housekeeping

### PR DESCRIPTION
**Pull request by ghost**
Housekeeping

### CODE REVIEW

**Comment by TamojitSaha** [comment]
> Check it @TamojitSaha

Please add the snippet lines

**Comment by SandeepanSengupta** [comment]
> > Check it @TamojitSaha
> 
> Please add the snippet lines

**_???_**

**Comment by TamojitSaha** [comment]
Ok, I found out that you declared the function. I overlooked.

More changes are to be made in the example sketches after which I will merge the pull request.

**Comment by SandeepanSengupta** [comment]
@TamojitSaha 
I have done some housekeeping, check them out brother

**Comment by TamojitSaha** [comment]
Done!

**Pull request merged**
